
version: 2

models:
  - name: snowflake_dbt_model
    description: "Model selecting from bookings staging table"
    columns:
      - name: booking_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: listing_id
        description: "Foreign key to listings table"
      - name: booking_date
        description: "Date of the booking"
      - name: nights_booked
        description: "Number of nights booked"
      - name: booking_amount
        description: "Total amount for the booking"
      - name: cleaning_fee
        description: "Cleaning fee charged"
      - name: service_fee
        description: "Service fee charged"
      - name: booking_status
        description: "Status of the booking"
      - name: created_at
        description: "Timestamp when the record was created"

  - name: listid_id_is_1
    description: "Filtered model for listing_id = 1"
    columns:
      - name: booking_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: listing_id
        description: "Foreign key to listings table, should be 1"
      - name: booking_date
        description: "Date of the booking"
      - name: nights_booked
        description: "Number of nights booked"
      - name: booking_amount
        description: "Total amount for the booking"
      - name: cleaning_fee
        description: "Cleaning fee charged"
      - name: service_fee
        description: "Service fee charged"
      - name: booking_status
        description: "Status of the booking"
      - name: created_at
        description: "Timestamp when the record was created"
